name: right_now
description: "A Legal Case trracker."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.0
  google_fonts: ^6.1.0
  dio: ^5.4.3+1
  image_picker: ^1.0.7
  camera: ^0.11.1
  path: ^1.8.3
  provider: ^6.0.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.0.0
  intl: ^0.18.0
  dotted_border: ^2.1.0
#  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/